import { app, BrowserWindow, dialog, ipcMain } from 'electron';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit();
}

// To prevent kWallet to delay launch by about a minute in KDE Plasma. No password is required throughout the app anyway.
app.commandLine.appendSwitch('password-store', 'basic');

function showErrorWindow(message: string) {
    const errorWindow = new BrowserWindow({
        height: 600,
        width: 800,
        resizable: false,
        minimizable: false,
        maximizable: false,
        title: 'Startup Error',
        webPreferences: {
            nodeIntegration: false,
            contextIsolation: false,
        }
    });

    // Load a simple HTML page showing the error
    errorWindow.loadURL(`data:text/html,
                        <html>
                        <head><title>Error</title></head>
                        <body style="font-family: sans-serif; display: flex; align-items: center; justify-content: center; height: 100vh; text-align: center;">
                        <h2>${message}</h2>
                        </body>
                        </html>`);
}

const createWindow = (): void => {
    // Create the browser window.
    const mainWindow = new BrowserWindow({
        height: 600,
        width: 800,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    ipcMain.handle('dialog:openDirectory', async () => {
        const { canceled, filePaths } = await dialog.showOpenDialog(mainWindow, {
            properties: ['openDirectory']
        })
        if (canceled) {
            return
        } else {
            return filePaths[0]
        }
    })

    ipcMain.handle(
        "api-request",
        async (
            event,
            args: {
                path: string;
                method: "GET" | "POST" | "PUT" | "DELETE";
                body?: any;
                headers?: Record<string, string>;
            }
        ) => {
            try {
                const response = await fetch(process.env.TAGGER_PLAYER_BACKEND_ADDRESS + args.path, {
                    method: args.method,
                    headers: {
                        "Content-Type": "application/json",
                        ...(args.headers || {}),
                    },
                    body: args.body ? JSON.stringify(args.body) : undefined,
                });

                const result = await response.json().catch(() => null); // Handle empty response
                return {
                    success: response.ok,
                    status: response.status,
                    data: result,
                };
            } catch (error: any) {
                return { success: false, error: error.message };
            }
        }
    );

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    // Open the DevTools.
    mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
    if (!process.env.TAGGER_PLAYER_BACKEND_ADDRESS) {
        showErrorWindow('The application cannot start because TAGGER_PLAYER_BACKEND_ADDRESS is not set.');
        return;
    }

    createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
